# Generated by Django 5.0.4 on 2024-06-24 15:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='Priority',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='epic',
            name='StoryPoint',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='issue',
            name='Priority',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='StoryPoint',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sprint',
            name='sprintName',
            field=models.CharField(default='', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(default='start', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='first_letter',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='epic',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='issue',
            name='IssueName',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='To-Do', max_length=30),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='sprint_goal',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommentId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('WrittenBy', models.CharField(default='', max_length=50)),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('EditedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('CommentBody', models.TextField(default='', max_length=300)),
                ('IssueId', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to='djapp.issue')),
                ('ProjectId', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djapp.project')),
            ],
        ),
    ]
